### ISSUE TITLE
Numba 0.45.1 gives error during import

### ISSUE THREAD

**Issue by patricio-astudillo** [pygae/clifford#230]
https://github.com/pygae/clifford/blob/aa01463a204a3fe4267c16dd1089835fee296ab9/requirements.txt#L3

This is fixed with version 0.48.0

**Comment by patricio-astudillo** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/clifford/tools/g3c/__init__.py", line 158, in <module>
    from clifford.tools.g3 import quaternion_to_rotor, random_euc_mv, \
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/clifford/tools/g3/__init__.py", line 49, in <module>
    from clifford.g3c import *
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/clifford/g3c.py", line 2, in <module>
    layout_orig, blades_orig = Cl(3)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/clifford/__init__.py", line 733, in Cl
    layout = Layout._from_Cl(p, q, r, firstIdx=firstIdx, names=names)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/clifford/_layout.py", line 163, in _from_Cl
    return cls._from_sig([0]*r + [+1]*p + [-1]*q, **kwargs)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/clifford/_layout.py", line 158, in _from_sig
    return cls(sig, bladeTupList, firstIdx=firstIdx, **kwargs)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/clifford/_layout.py", line 146, in __init__
    self._genTables()
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/clifford/_layout.py", line 313, in _genTables
    self.omt = sparse.where(omt_prod_mask, self.gmt, self.gmt.dtype.type(0))
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/sparse/_coo/common.py", line 817, in where
    return elemwise(np.where, condition, x, y)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/sparse/_coo/umath.py", line 48, in elemwise
    return _Elemwise(func, *args, **kwargs).get_result()
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/sparse/_coo/umath.py", line 478, in get_result
    r = self._get_func_coords_data(mask)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/sparse/_coo/umath.py", line 607, in _get_func_coords_data
    *matched_args, cache=self.cache, broadcast_shape=matched_broadcast_shape
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/sparse/_coo/umath.py", line 739, in _match_coo
    matched_idx = _match_arrays(*linear)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/dispatcher.py", line 395, in _compile_for_args
    raise e
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler.py", line 266, in run
    raise patched_exception
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler.py", line 257, in run
    stage()
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler.py", line 764, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler.py", line 690, in backend_nopython_mode
    self.metadata)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/compiler.py", line 1143, in native_lowering_stage
    lower.lower()
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/errors.py", line 670, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "../../../../../anaconda3/envs/myGA/lib/python3.6/site-packages/sparse/_coo/umath.py", line 71:
def _match_arrays(a, b):  # pragma: no cover
    <source elided>

    a_ind, b_ind = [], []
    ^

[1] During: lowering "$56.1 = build_list(items=[])" at /home/patricio/anaconda3/envs/myGA/lib/python3.6/site-packages/sparse/_coo/umath.py (71)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by eric-wieser** [comment]
This was fixed in #225, I guess we need to do a release

**Comment by eric-wieser** [comment]
In the meantime, you can work around this by installing the newest numba even though clifford asks for the old one.
