### ISSUE TITLE
Errors installing Clifford in Python version 3.9.

### ISSUE THREAD

**Issue by nyle12345** [pygae/clifford#380]
Having trouble with supporting libraries/modules that are installed along side Clifford.  Please see errors below.

C:\Users\rashe\AppData\Local\Programs\Python\Python39\Scripts>pip3 install clifford "numba~=0.48.0" "sparse~=0.9.0"
Collecting numba~=0.48.0
  Using cached numba-0.48.0.tar.gz (2.0 MB)
Requirement already satisfied: numpy>=1.15 in c:\users\rashe\appdata\local\programs\python\python39\lib\site-packages (from numba~=0.48.0) (1.19.3)
Requirement already satisfied: setuptools in c:\users\rashe\appdata\local\programs\python\python39\lib\site-packages (from numba~=0.48.0) (49.2.1)
Collecting sparse~=0.9.0
  Using cached sparse-0.9.1-py2.py3-none-any.whl (63 kB)
Requirement already satisfied: scipy>=0.19 in c:\users\rashe\appdata\local\programs\python\python39\lib\site-packages (from sparse~=0.9.0) (1.5.4)
Collecting llvmlite<0.32.0,>=0.31.0dev0
  Using cached llvmlite-0.31.0.tar.gz (110 kB)
Collecting clifford
  Using cached clifford-1.3.1-py3-none-any.whl (142 kB)
Collecting h5py
  Using cached h5py-3.1.0-cp39-cp39-win_amd64.whl (2.7 MB)
Using legacy 'setup.py install' for numba, since package 'wheel' is not installed.
Using legacy 'setup.py install' for llvmlite, since package 'wheel' is not installed.
Installing collected packages: llvmlite, numba, sparse, h5py, clifford
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\rashe\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\rashe\\AppData\\Local\\Temp\\pip-install-84b1asc7\\llvmlite_fa79b7393761491c802fbf7bf2394105\\setup.py'"'"'; __file__='"'"'C:\\Users\\rashe\\AppData\\Local\\Temp\\pip-install-84b1asc7\\llvmlite_fa79b7393761491c802fbf7bf2394105\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\rashe\AppData\Local\Temp\pip-record-eu1n6pud\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\rashe\appdata\local\programs\python\python39\Include\llvmlite'
         cwd: C:\Users\rashe\AppData\Local\Temp\pip-install-84b1asc7\llvmlite_fa79b7393761491c802fbf7bf2394105\
    Complete output (27 lines):
    running install
    running build
    got version from file C:\Users\rashe\AppData\Local\Temp\pip-install-84b1asc7\llvmlite_fa79b7393761491c802fbf7bf2394105\llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
    running build_ext
    c:\users\rashe\appdata\local\programs\python\python39\python.exe C:\Users\rashe\AppData\Local\Temp\pip-install-84b1asc7\llvmlite_fa79b7393761491c802fbf7bf2394105\ffi\build.py
    Trying generator 'Visual Studio 14 2015 Win64'
    Traceback (most recent call last):
      File "C:\Users\rashe\AppData\Local\Temp\pip-install-84b1asc7\llvmlite_fa79b7393761491c802fbf7bf2394105\ffi\build.py", line 168, in <module>
        main()
      File "C:\Users\rashe\AppData\Local\Temp\pip-install-84b1asc7\llvmlite_fa79b7393761491c802fbf7bf2394105\ffi\build.py", line 156, in main
        main_win32()
      File "C:\Users\rashe\AppData\Local\Temp\pip-install-84b1asc7\llvmlite_fa79b7393761491c802fbf7bf2394105\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\rashe\AppData\Local\Temp\pip-install-84b1asc7\llvmlite_fa79b7393761491c802fbf7bf2394105\ffi\build.py", line 76, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\rashe\AppData\Local\Temp\pip-install-84b1asc7\llvmlite_fa79b7393761491c802fbf7bf2394105\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "c:\users\rashe\appdata\local\programs\python\python39\lib\subprocess.py", line 368, in check_call
        retcode = call(*popenargs, **kwargs)
      File "c:\users\rashe\appdata\local\programs\python\python39\lib\subprocess.py", line 349, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\users\rashe\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "c:\users\rashe\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    error: command 'c:\\users\\rashe\\appdata\\local\\programs\\python\\python39\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\rashe\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\rashe\\AppData\\Local\\Temp\\pip-install-84b1asc7\\llvmlite_fa79b7393761491c802fbf7bf2394105\\setup.py'"'"'; __file__='"'"'C:\\Users\\rashe\\AppData\\Local\\Temp\\pip-install-84b1asc7\\llvmlite_fa79b7393761491c802fbf7bf2394105\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\rashe\AppData\Local\Temp\pip-record-eu1n6pud\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\rashe\appdata\local\programs\python\python39\Include\llvmlite' Check the logs for full command output.

**Comment by hugohadfield** [comment]
Hi, this looks like a Python 3.9 compatibility issue to me. The numba JIT compiler that clifford uses does not quite yet support Python 3.9, see https://github.com/numba/numba/issues/6345 , looks like they are planning support for 3.9 sometime early in the new year so probably best to use python 3.8 in the meantime

**Comment by nyle12345** [comment]
Thank-you Arthur!!!
    On Friday, December 25, 2020, 05:25:57 a.m. PST, hugohadfield <notifications@github.com> wrote:  
 
 


Hi, this looks like a Python 3.9 compatibility issue to me. The numba JIT compiler that clifford uses does not quite yet support Python 3.9, see numba/numba#6345 , looks like they are planning support for 3.9 sometime early in the new year so probably best to use python 3.8 in the meantime

**Comment by hendursaga** [comment]
This appears to work now, under Python 3.9.19 but only with numba 0.58.1, before the removal of `generated_jit`. Close?
