### ISSUE TITLE
Brew version

### ISSUE THREAD

**Issue by nwikner** [pygae/clifford#421]
My python installation on my Mac is via Brew.  There seems to be no brew "Tap" for Clifford, and pip3 clifford fails.  What to do?

**Comment by eric-wieser** [comment]
Can you show the error message you get for `pip3 install clifford`?

**Comment by nwikner** [comment]
***@***.*** ~ % pip3 install clifford                                              
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting clifford
  Using cached clifford-1.4.0-py3-none-any.whl (159 kB)
Collecting numba>0.46
  Using cached numba-0.55.1.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... done
Collecting scipy
  Using cached scipy-1.8.0-cp39-cp39-macosx_12_0_arm64.whl (28.7 MB)
Collecting sparse
  Using cached sparse-0.13.0-py2.py3-none-any.whl (77 kB)
Collecting h5py
  Using cached h5py-3.6.0.tar.gz (384 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.17
  Using cached numpy-1.22.3-cp39-cp39-macosx_11_0_arm64.whl (12.8 MB)
Collecting llvmlite<0.39,>=0.38.0rc1
  Using cached llvmlite-0.38.0.tar.gz (129 kB)
  Preparing metadata (setup.py) ... done
Collecting numpy>=1.17
  Using cached numpy-1.21.6-cp39-cp39-macosx_11_0_arm64.whl (12.4 MB)
Requirement already satisfied: setuptools in /opt/homebrew/lib/python3.9/site-packages (from numba>0.46->clifford) (60.10.0)
Building wheels for collected packages: numba, h5py, llvmlite
  Building wheel for numba (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/52/ktwl61n14ggd66vq53lbclmh0000gp/T/pip-install-rji8vox1/numba_3e06bacda77f40f1bed445322e6e1d5d/setup.py", line 413, in <module>
          metadata['ext_modules'] = get_ext_modules()
        File "/private/var/folders/52/ktwl61n14ggd66vq53lbclmh0000gp/T/pip-install-rji8vox1/numba_3e06bacda77f40f1bed445322e6e1d5d/setup.py", line 141, in get_ext_modules
          import numpy.distutils.misc_util as np_misc
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for h5py (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for h5py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-3.9
      creating build/lib.macosx-12-arm64-3.9/h5py
      copying h5py/h5py_warnings.py -> build/lib.macosx-12-arm64-3.9/h5py
      copying h5py/version.py -> build/lib.macosx-12-arm64-3.9/h5py
      copying h5py/__init__.py -> build/lib.macosx-12-arm64-3.9/h5py
      copying h5py/ipy_completer.py -> build/lib.macosx-12-arm64-3.9/h5py
      creating build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/files.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/compat.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/__init__.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/selections.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/dataset.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/vds.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/selections2.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/group.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/datatype.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/attrs.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/dims.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/base.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      copying h5py/_hl/filters.py -> build/lib.macosx-12-arm64-3.9/h5py/_hl
      creating build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_dimension_scales.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_attribute_create.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_file_image.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/conftest.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_h5f.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_dataset_getitem.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_group.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_errors.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_dataset_swmr.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_slicing.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_h5pl.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_attrs.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/__init__.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_attrs_data.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_h5t.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_big_endian_file.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_h5p.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_h5o.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_datatype.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/common.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_dataset.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_file.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_selections.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_dtype.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_h5.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_file2.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_completions.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_filters.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_base.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      copying h5py/tests/test_objects.py -> build/lib.macosx-12-arm64-3.9/h5py/tests
      creating build/lib.macosx-12-arm64-3.9/h5py/tests/data_files
      copying h5py/tests/data_files/__init__.py -> build/lib.macosx-12-arm64-3.9/h5py/tests/data_files
      creating build/lib.macosx-12-arm64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.macosx-12-arm64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.macosx-12-arm64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/__init__.py -> build/lib.macosx-12-arm64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.macosx-12-arm64-3.9/h5py/tests/test_vds
      copying h5py/tests/data_files/vlen_string_s390x.h5 -> build/lib.macosx-12-arm64-3.9/h5py/tests/data_files
      copying h5py/tests/data_files/vlen_string_dset_utc.h5 -> build/lib.macosx-12-arm64-3.9/h5py/tests/data_files
      copying h5py/tests/data_files/vlen_string_dset.h5 -> build/lib.macosx-12-arm64-3.9/h5py/tests/data_files
      running build_ext
      Loading library to get build settings and version: libhdf5.dylib
      error: Unable to load dependency HDF5, make sure HDF5 is installed properly
      error: dlopen(libhdf5.dylib, 0x0006): tried: '/opt/homebrew/lib/libhdf5.dylib' (no such file), '/opt/homebrew/lib/libhdf5.dylib' (no such file), 'libhdf5.dylib' (no such file), '/usr/local/lib/libhdf5.dylib' (no such file), '/usr/lib/libhdf5.dylib' (no such file), '/private/var/folders/52/ktwl61n14ggd66vq53lbclmh0000gp/T/pip-install-rji8vox1/h5py_c52b61d029a744c9bcfd88afbcad72a5/libhdf5.dylib' (no such file)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      ***@***.***/bin/python3.9 /private/var/folders/52/ktwl61n14ggd66vq53lbclmh0000gp/T/pip-install-rji8vox1/llvmlite_2a298f57c5a147ea820d3138baabc021/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/private/var/folders/52/ktwl61n14ggd66vq53lbclmh0000gp/T/pip-install-rji8vox1/llvmlite_2a298f57c5a147ea820d3138baabc021/ffi/build.py", line 220, in <module>
          main()
        File "/private/var/folders/52/ktwl61n14ggd66vq53lbclmh0000gp/T/pip-install-rji8vox1/llvmlite_2a298f57c5a147ea820d3138baabc021/ffi/build.py", line 214, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/52/ktwl61n14ggd66vq53lbclmh0000gp/T/pip-install-rji8vox1/llvmlite_2a298f57c5a147ea820d3138baabc021/ffi/build.py", line 134, in main_posix
          raise RuntimeError(msg) from None
      RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
      error: command ***@***.***/bin/python3.9' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build numba h5py llvmlite
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects

On May 12, 2022, at 4:19 PM, Eric Wieser ***@***.***> wrote:


Can you show the error message you get for pip3 install clifford?

**Comment by eric-wieser** [comment]
Does `pip3 install numba` work for you? It looks like the problem is with numba, not with `clifford`.

**Comment by nwikner** [comment]
no, it did not.  It failed because it couldn't find numpy. I have numpy in my brew distribution of python, and I can run galgebra from within jupyter.  But the locations of these things are not where pip3 is expecting them.
