### ISSUE TITLE
Installing on windows fails

### ISSUE THREAD

**Issue by utensil** [pygae/clifford#85]
Following https://clifford.readthedocs.io/en/latest/Installation.html, I tried the following in a Conda Python 3 environment:

```bash
pip install clifford
```

It fails with the following error(only the relevant part ):

```bash
Building wheels for collected packages: future, llvmlite
(omitted)
-- Detecting CXX compile features - done
  CMake Error at CMakeLists.txt:9 (find_package):
    Could not find a package configuration file provided by "LLVM" with any of
    the following names:

      LLVMConfig.cmake
      llvm-config.cmake

    Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
    "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
    provides a separate development package or SDK, be sure it has been
    installed.


  -- Configuring incomplete, errors occurred!
  See also "E:/Temp/pip-install-zgckej4r/llvmlite/ffi/build/CMakeFiles/CMakeOutput.log".
  Trying generator 'Visual Studio 14 2015 Win64'
  Traceback (most recent call last):
    File "E:\Temp\pip-install-zgckej4r\llvmlite\ffi\build.py", line 167, in <module>
      main()
    File "E:\Temp\pip-install-zgckej4r\llvmlite\ffi\build.py", line 155, in main
      main_win32()
    File "E:\Temp\pip-install-zgckej4r\llvmlite\ffi\build.py", line 93, in main_win32
      try_cmake(here_dir, build_dir, generator)
    File "E:\Temp\pip-install-zgckej4r\llvmlite\ffi\build.py", line 28, in try_cmake
      subprocess.check_call(['cmake', '-G', generator, cmake_dir])
    File "E:\Miniconda3\envs\py3\lib\subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-G', 'Visual Studio 14 2015 Win64', 'E:\\Temp\\pip-install-zgckej4r\\llvmlite\\ffi']' returned non-zero exit status 1.
  error: command 'E:\\Miniconda3\\envs\\py3\\python.exe' failed with exit status 1

  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built future
Failed to build llvmlite
```

I believe this dependencies and possible trouble shooting should be addressed in doc. But anyway, as long as it's a native building problem, we can alway see if conda can help:

```bash
conda install clifford
```

Then there's PackagesNotFoundError.

So I take a look at https://github.com/pygae/clifford/blob/master/azure-pipelines.yml and tried the following:

```bash
conda install -y future h5py nose pytest setuptools scipy numpy
conda install -y numba=0.40.1
pip install clifford
```

Everything went smoothly, time to use `clifford`! Unfortunately:

```python
>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from clifford.tools.g3c import random_line
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Miniconda3\envs\py3\lib\site-packages\clifford\tools\g3c\__init__.py", line 133, in <module>
    from clifford.tools.g3 import quaternion_to_rotor, random_euc_mv, \
  File "E:\Miniconda3\envs\py3\lib\site-packages\clifford\tools\g3\__init__.py", line 49, in <module>
    from clifford.g3c import *
  File "E:\Miniconda3\envs\py3\lib\site-packages\clifford\g3c.py", line 3, in <module>
    layout_orig, blades_orig = Cl(3)
  File "E:\Miniconda3\envs\py3\lib\site-packages\clifford\__init__.py", line 2286, in Cl
    layout = Layout(sig, bladeTupList, firstIdx=firstIdx, names=names)
  File "E:\Miniconda3\envs\py3\lib\site-packages\clifford\__init__.py", line 620, in __init__
    self._genTables()
  File "E:\Miniconda3\envs\py3\lib\site-packages\clifford\__init__.py", line 719, in _genTables
    np.array(self.sig))
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\dispatcher.py", line 367, in _compile_for_args
    raise e
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\compiler.py", line 904, in compile_extra
    return pipeline.compile_extra(func)
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\compiler.py", line 835, in _compile_bytecode
    return self._compile_core()
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\compiler.py", line 822, in _compile_core
    res = pm.run(self.status)
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\compiler.py", line 253, in run
    raise patched_exception
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\compiler.py", line 244, in run
    stage()
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\compiler.py", line 539, in stage_parfor_pass
    parfor_pass.run()
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\parfor.py", line 682, in run
    self.array_analysis.run(self.func_ir.blocks)
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\array_analysis.py", line 906, in run
    equiv_set = equiv_set.intersect(from_set)
  File "E:\Miniconda3\envs\py3\lib\site-packages\numba\array_analysis.py", line 537, in intersect
    assert(len(varlist) > 0)
AssertionError: Failed in nopython mode pipeline (step: convert to parfors)
```

I haven't figured out what these mean yet, just searched that there's no similar issue and opened this one.

**Comment by utensil** [comment]
There're issues with similar error in numba but not exactly the same and all were marked fixed.

**Comment by hugohadfield** [comment]
Ah, yes this is annoying
If you are on conda run:

```
conda install -c numba/label/dev numba
```

We should be getting a new release of numba any day now that will fix all our problems (hopefully!)
Let me know how the above goes!

**Comment by utensil** [comment]
Yeah. now `clifford` can be imported, but when I followed https://github.com/pygae/pyganja#use and did:

```python
from clifford.tools.g3c import random_line
from pyganja import *

draw([random_line() for i in range(10)])
```

It fails with:

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\projects\pyganja\pyganja\script_api.py", line 237, in draw
    render_scene_string_appropriately(str(sc))
  File "E:\projects\pyganja\pyganja\script_api.py", line 223, in render_scene_string_appropriately
    render_cef_script(scene_string, sig=sig, grid=grid, scale=scale, gl=gl)
  File "E:\projects\pyganja\pyganja\script_api.py", line 185, in render_cef_script
    p.start()
  File "E:\Miniconda3\envs\py3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "E:\Miniconda3\envs\py3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\Miniconda3\envs\py3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\Miniconda3\envs\py3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\Miniconda3\envs\py3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'render_cef_script.<locals>.render_script'
>>> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Miniconda3\envs\py3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Miniconda3\envs\py3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by hugohadfield** [comment]
Yep that is a problem with pyganja on windows cefpython fails to load and you get problems...
You can get round it by passing `browser_window=True` to your draw call eg:
```
from clifford.tools.g3c import random_line
from pyganja import *

draw([random_line() for i in range(10)],browser_window=True)
```
to force pyganja to render via the browser in a tab rather than in a new cefpython window, alternatively using pyganja in jupyter works really nicely... reminds me I need to spend a while sorting out windows pyganja problems :(

**Comment by utensil** [comment]
Thanks, that went very well. Yes, I've already tried it in a jupyter notebook in binder and under Windows, it's  awesome!

I'll close this issue as it's now solved and could be served as temp doc for someone who encounter the same issue.

**Comment by hugohadfield** [comment]
The latest release of numba (0.43) which came out today should fix all the problems with clifford on windows :) https://anaconda.org/numba/numba/ https://pypi.org/project/numba/
Give it a try!
