### ISSUE TITLE
Build failure :: numba-integration-testing

### ISSUE THREAD

**Issue by esc** [pygae/clifford#94]
I am currently seeing a test failure in the numba-integration-testing framework:

```
======================================================================
FAIL: test_general_logarithm_rotation (test_g3c_tools.TestGeneralLogarithm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/repo/clifford/test/test_g3c_tools.py", line 95, in test_general_logarithm_rotation
    np.testing.assert_almost_equal(biv_2.value, biv_3.value, 3)
  File "/home/circleci/repo/miniconda3/envs/clifford/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 572, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/home/circleci/repo/miniconda3/envs/clifford/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1007, in assert_array_almost_equal
    precision=decimal)
  File "/home/circleci/repo/miniconda3/envs/clifford/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 819, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 3 decimals

Mismatch: 9.38%
Max absolute difference: 1.38089358
Max relative difference: nan
 x: array([-0.000e+00, -0.000e+00, -0.000e+00, -0.000e+00, -0.000e+00,
       -0.000e+00,  1.535e-05, -6.327e-06, -0.000e+00, -0.000e+00,
        5.405e-06, -0.000e+00, -0.000e+00, -0.000e+00, -0.000e+00,...
 y: array([ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.381, -0.569,
        0.   ,  0.   ,  0.486,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ])

----------------------------------------------------------------------
```

The build log can be seen here: https://circleci.com/gh/numba/numba-integration-testing/323

**Comment by esc** [comment]
FWIW: I just wanted to bring this to your attention, I am pretty sure that this will probably not have anything to do with a Numba upstream change.

**Comment by hugohadfield** [comment]
Yes thanks @esc this is definitely our fault, some stability issue with the exponential/logarithm functions :'(

**Comment by esc** [comment]
@hugohadfield I concur, for example today the test ran through fine, perhaps there are some numerical instabilities in the test? Probably just enough to reduce the accuracy during comparison.
